apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
      - name: java-demo
        image: registry.cn-hangzhou.aliyuncs.com/k8scicd/cicd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: java-demo
  selector:
    app: java-demo
  type: LoadBalancer